build:
  # @ to suppress the output of the command
	@go build -o bin/fact

run: build
  # running the output
	./bin/fact

test:
  # test run test in verbose mode is all dir and subdirectories
	go test -v ./...
